@ECHO OFF

ECHO GENERATING GIT_VERSION

FOR /F "delims=" %%i IN ('git describe --tags --always --dirty --long') DO SET "GIT_VERSION=%%i"
FOR /F "delims=" %%i IN ('git rev-parse --abbrev-ref HEAD') DO SET "GIT_BRANCH=%%i"

SET "GIT_VERSION=%GIT_VERSION%"
SET "GIT_BRANCH=%GIT_BRANCH%"
SET "GIT_BUILD=%GIT_BRANCH%@%GIT_VERSION%"

ECHO GIT_VERSION=%GIT_VERSION%
ECHO GIT_BRANCH=%GIT_BRANCH%
ECHO GIT_BUILD=%GIT_BUILD%

(
    ECHO GIT_VERSION="%GIT_VERSION%";
    ECHO GIT_BRANCH="%GIT_BRANCH%";
    ECHO GIT_BUILD="%GIT_BUILD%";
) > GIT_VERSION.scad